package se.umu.cs.warn.buster.thirtygame.model_high_score;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

/**
 * Implementation of Entity in room database. The entity represents a table in the Room database.
 *
 * The entity consists of a uid - the primary key which is autogenerated, a name as a string and a
 * score as an int.
 *
 * @See <a href="https://developer.android.com/training/data-storage/room/defining-data">Defining
 * data using Room entities</a>
 *
 * Author:          Buster Hultgren Wärn - busterw@cs.umu.se.
 * Course:          Application in mobile development.
 * Written:         2020-07-23.
 */
@Entity(tableName = "high_scores")
public class ScoreEntity {

    @PrimaryKey(autoGenerate = true)
    public int uid;

    @ColumnInfo(name = "name")
    public String name;

    @ColumnInfo(name = "score")
    public int score;

    /**
     * Constructor for database entry.
     * @param uid Primary key
     * @param name Name
     * @param score Score
     */
    public ScoreEntity(int uid, String name, int score) {
        this.uid = uid;
        this.name = name;
        this.score = score;
    }

    /**
     * Constructor for database entry.
     * @param name Name
     * @param score Score
     */
    @Ignore
    public ScoreEntity(String name, int score) {
        this.name = name;
        this.score = score;
    }
}
